### PR TITLE
Flush

### LINKED ISSUE #30: Notify keeps pending, does not return the channelID
`curl -k 'https://localhost:8000/system/icc/notify?meeting_id=1'`
returns
`{"error":"not-allowed","msg":"Anonymous user can not receive notify messages."}`

Thus, ICC is obviously reachable and integrated.

The request that the client send towards icc, however:

```
curl -k 'https://localhost:8000/system/icc/notify?meeting_id=1' \                                                                                         ±[●][fix-icc-integration]
  -H 'authority: localhost:8000' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96"' \
  -H 'dnt: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJlZjQxYjFkZDM4NDk4ODc2ODM2NWU0MGQ5MjI0NzUwMyIsInVzZXJJZCI6MSwiaWF0IjoxNjM4NzkzMDI5LCJleHAiOjE2Mzg3OTM2Mjl9.4RIoE2j5Xnr6TiWniKnSahuyO7wKT65PNDQKg_XaWr8' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://localhost:8000/1' \
  -H 'accept-language: de-DE,de;q=0.9,en-DE;q=0.8,en;q=0.7,en-US;q=0.6' \
  -H 'cookie: refreshId=bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJlZjQxYjFkZDM4NDk4ODc2ODM2NWU0MGQ5MjI0NzUwMyIsInVzZXJJZCI6MSwiaWF0IjoxNjM4Nzg3NzUwLCJleHAiOjE2Mzg4NzQxNTB9.vVM3uratBDe0v1LEGW8Fn69D9yzQ1dW_a2YgErOjfYE' \
  --compressed
```

stays in pending state until the timeout it reached. It never returns anything.

To reproduce, check out OpenSlides at https://github.com/OpenSlides/OpenSlides/pull/6305
Log into a **meeting** via the client 

find the following request in the browser network view
image

right click -> copy -> copy as curl

### PR DESCRIPTION
**Pull request by ostcar**
Fixes #30 

Also sets the default port to 9007. See https://github.com/OpenSlides/OpenSlides/wiki/DE%3AKonzept-OpenSlides-4#default-ports

@gsiv and @peb-adr I set a wrong default port. The current default port is 9013, which is the port of the vote-servie. I don't think that this change will be any problem, since you set the default port in the proxy: https://github.com/OpenSlides/OpenSlides/blob/fd3371dd0b11f49e6cbaccdafed4d3c966efe6c4/proxy/entrypoint#L15

But I think you should change them in the main repo (low priority)

@normanjaeckel the same for the manage-service: https://github.com/OpenSlides/openslides-manage-service/blob/16ad83cb13d18588fdb743e099a059a028eac88c/pkg/config/default-config.yml#L74

### CODE REVIEW

**Comment by peb-adr** [comment]
@tsiegleauq already did a corresponding in the main repo, hower he used port 9009, you should agree on one.
Both are unused atm so for me either fine.

**Comment by ostcar** [comment]
We documented the ports. See my link above. 

9009 is for the search (if it will ever exist).

**Review by tsiegleauq — CHANGES_REQUESTED** [review]
* checked out 838429703b099eea2140d5f811ab6e33b99e5bd7
* run `docker build -t openslides-proxy-dev -f Dockerfile.dev . --no-cache`
* `make stop dev` in os
* `make run dev` in os
* changed ports in the open pr

The problem still persists. If I did not forger anything it does not fix #30

**Review by tsiegleauq — APPROVED** [review]
ok it'll work when the reverse proxy has `"flush_interval": -1,`.
Don't really know what it does tho, but in this case it's required.

Can confirm this works together with the current PR.

Squash and merge at will.

**Pull request merged**
