### PR TITLE
Update autoupdate service

### PR DESCRIPTION
**Pull request by ostcar**

### CODE REVIEW

**Review by emanuelschuetze — CHANGES_REQUESTED** [review]
Try to send applause in a meeting as superadmin:
`Error: not-allowed, Msg: Anonymous user can not send applause.`

**Comment by emanuelschuetze** [comment]
Works after restart of dev setup. But I get no response -> no applause value...

**Comment by ostcar** [comment]
> Works after restart of dev setup. But I get no response -> no applause value...

What do you mean with "no response"? The request to applause/send does not sent a response? I would expect a response with status 200. The applause/send handler is non blocking. If you have to wait, then there is an error.

The client receives the applause on a different url that is blocking. You can use the performance tool to test it:

```
openslides-performance request /system/icc//applause?meeting_id=1
```

**Comment by ostcar** [comment]
I can not reproduce this, because I don't know how to activate applause for a meeting in the client.

Please use the following commands to test it.

```
go install github.com/OpenSlides/openslides-performance@latest
openslides-performance request /system/icc/applause?meeting_id=1
```

Then send applause with this command in another tab:

```
openslides-performance request /system/icc/applause/send?meeting_id=1
```

**Review by emanuelschuetze — APPROVED** [review]
performance command works for me.

**Pull request merged**
